name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have reviewed and hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Pin to a specific version - this third-party action uses a personal access token
        uses: cla-assistant/github-action@f41946747f85d28e9a738f4f38dbcc74b69c7e0e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_PERSONAL_ACCESS_TOKEN }}
        with:
          # Signatures are stored in https://github.com/EarthSciML/cla
          remote-organization-name: EarthSciML 
          remote-repository-name: cla 
          path-to-signatures: signatures.json
          path-to-document: https://github.com/EarthSciML/cla/blob/main/CLA.md
          branch: main
          allowlist: dependabot[bot]
          custom-pr-sign-comment: I have reviewed and hereby sign the CLA
          create-file-commit-message: Create signatures.json
          signed-commit-message: '$contributorName signed the CLA in $pullRequestNo'
          custom-notsigned-prcomment: 'Thanks for your contribution! Like many open source projects, we ask that you sign our [Contributor License Agreement](https://github.com/EarthSciML/cla/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by posting a comment with the below format:<br/>'
